#apache host (sem provisionamento tendo em vista que farei pelo ansible)

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "private_network", ip: "192.168.2.12
  config.vm.synced_folder "/home/felipe/My Projects/Ansible-lab-estudos/ansible-host/sync", "/ansible"  
end
